/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import prom.*;

/**
 *
 * @author AlphaBeta's
 */
public class Customer_Register extends javax.swing.JFrame {

    /**
     * Creates new form Student_Registering
     */
    public Customer_Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nm_label = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        address_label = new javax.swing.JLabel();
        addressfield = new javax.swing.JTextField();
        pas_label = new javax.swing.JLabel();
        register_btn = new javax.swing.JButton();
        bckbtn = new javax.swing.JButton();
        passfield = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stu.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        nm_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nm_label.setForeground(new java.awt.Color(255, 255, 255));
        nm_label.setText("Name:");
        getContentPane().add(nm_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        namefield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 190, -1));

        email_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        email_label.setForeground(new java.awt.Color(255, 255, 255));
        email_label.setText("Email:");
        getContentPane().add(email_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        emailfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 190, -1));

        address_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        address_label.setForeground(new java.awt.Color(255, 255, 255));
        address_label.setText("Address:");
        getContentPane().add(address_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        addressfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 190, -1));

        pas_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pas_label.setForeground(new java.awt.Color(255, 255, 255));
        pas_label.setText("Password:");
        getContentPane().add(pas_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        register_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        register_btn.setText("Register");
        register_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_btnActionPerformed(evt);
            }
        });
        getContentPane().add(register_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 120, 40));

        bckbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bckbtn.setText("Back");
        bckbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bckbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckbtnActionPerformed(evt);
            }
        });
        getContentPane().add(bckbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        passfield.setText("passwordfield");
        passfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passfieldActionPerformed(evt);
            }
        });
        getContentPane().add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 190, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stu.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_btnActionPerformed
       User std = new User();
       String name = namefield.getText();
       String email = emailfield.getText();
       String pass = passfield.getText();
       String address = addressfield.getText();       
        std.setId(User.generateId());   
        String password = hashing_code.hashpassword(pass);
        String detail = std.getId()+"||"+name+"||"+email+"||"+address+"||"+password;
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter("D:\\netbeans_projects\\JavaApplication2\\textfile\\stu_detail.txt",true));
            writer.write(detail);
            writer.newLine();
            writer.flush();
            writer.close();
            JOptionPane.showMessageDialog(this,"Registration Sucessfull");
            JOptionPane.showMessageDialog(this,"Your ID is:"+std.getId());
            namefield.setText("");
            emailfield.setText("");
            passfield.setText("");
            addressfield.setText("");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
        
    }//GEN-LAST:event_register_btnActionPerformed

    private void bckbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckbtnActionPerformed
        Customer_Login stdlg = new Customer_Login();
        stdlg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bckbtnActionPerformed

    private void passfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address_label;
    private javax.swing.JTextField addressfield;
    private javax.swing.JButton bckbtn;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField namefield;
    private javax.swing.JLabel nm_label;
    private javax.swing.JLabel pas_label;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JButton register_btn;
    // End of variables declaration//GEN-END:variables
}
