/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author AlphaBeta's
 */
public class Feedback_GUI extends javax.swing.JFrame {

    /**
     * Creates new form feedbackgui
     */
    public Feedback_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        feback = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedfield = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        feedbtn = new javax.swing.JButton();
        namefield = new javax.swing.JTextField();
        npifield = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome To Feedback Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 8, -1, -1));

        feback.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        feback.setForeground(new java.awt.Color(255, 255, 255));
        feback.setText("Your Feedback Here");
        getContentPane().add(feback, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 37, -1, -1));

        feedfield.setColumns(20);
        feedfield.setRows(5);
        jScrollPane1.setViewportView(feedfield);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 61, 343, 217));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please Provide Your Name And Code:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 61, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 106, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Your NPI Code:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 166, -1, -1));

        feedbtn.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        feedbtn.setText("Feedback");
        feedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbtnActionPerformed(evt);
            }
        });
        getContentPane().add(feedbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 236, -1, -1));
        getContentPane().add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 105, 162, -1));
        getContentPane().add(npifield, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 165, 162, -1));

        backbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backbtn.setText("<<Go Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbtnActionPerformed
            String name = namefield.getText();
            String code = npifield.getText();
            String feedback = feedfield.getText();
            
            String feedbackData = "Name:" +name+ "\nCode: "+code+"\nFeedback:"  +feedback+"\n";
            
            String filePath = "D:\\netbeans_projects\\JavaApplication2\\textfile\\feedback.txt";
            
            try(BufferedWriter writer = new BufferedWriter(new FileWriter(filePath,true))){
                writer.write(feedbackData);
                writer.newLine();
                writer.flush();
                writer.close();
                
                JOptionPane.showMessageDialog(this,"Thank You For Your Feedback");
            }
            catch(IOException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(this,"An error has occured!!!");
            }
            
            namefield.setText("");
            npifield.setText("");
            feedfield.setText("");
    }//GEN-LAST:event_feedbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
            User_DashBoard stdsh = new User_DashBoard("");
            stdsh.setVisible(true);
            this.hide();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedback_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedback_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedback_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedback_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedback_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel feback;
    private javax.swing.JButton feedbtn;
    private javax.swing.JTextArea feedfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField npifield;
    // End of variables declaration//GEN-END:variables
}
