/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author AlphaBeta's
 */
public class Manager_DashBoard extends javax.swing.JFrame {
    /**
     * Creates new form manager_dash
     */
    public Manager_DashBoard() {
        initComponents();
        currentimedate( );
       
    }
        public  void currentimedate(){
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss a");
        datefield.setText(now.format(dtf));
        datefield.repaint();
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        updatemenu = new javax.swing.JButton();
        orderhistory = new javax.swing.JButton();
        feedback = new javax.swing.JButton();
        signout = new javax.swing.JButton();
        datefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome Manager");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        updatemenu.setBackground(new java.awt.Color(204, 204, 204));
        updatemenu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updatemenu.setText("Update Menu");
        updatemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemenuActionPerformed(evt);
            }
        });
        getContentPane().add(updatemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, 70));

        orderhistory.setBackground(new java.awt.Color(204, 204, 204));
        orderhistory.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        orderhistory.setText("Order History");
        orderhistory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orderhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderhistoryActionPerformed(evt);
            }
        });
        getContentPane().add(orderhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 140, 60));

        feedback.setBackground(new java.awt.Color(204, 204, 204));
        feedback.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        feedback.setText("See Feedback");
        feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackActionPerformed(evt);
            }
        });
        getContentPane().add(feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 140, 60));

        signout.setBackground(new java.awt.Color(102, 102, 255));
        signout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setText("SignOut");
        signout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });
        getContentPane().add(signout, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 100, 40));

        datefield.setEditable(false);
        datefield.setToolTipText("");
        getContentPane().add(datefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dahs.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemenuActionPerformed
    Update_Menu  updatemenu = new Update_Menu();
    updatemenu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_updatemenuActionPerformed

    private void orderhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderhistoryActionPerformed
      History his = new History();
      his.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_orderhistoryActionPerformed

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
        Manager_Login mglg = new Manager_Login();
        mglg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signoutActionPerformed

    private void feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackActionPerformed
    Feedback fcbk = new Feedback();
    fcbk.setVisible(true);
    this.hide();
    }//GEN-LAST:event_feedbackActionPerformed

    /**
     * @param args the command line arguments    public static void main(String args[]) {

     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datefield;
    private javax.swing.JButton feedback;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton orderhistory;
    private javax.swing.JButton signout;
    private javax.swing.JButton updatemenu;
    // End of variables declaration//GEN-END:variables
}
