/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author AlphaBeta's
 */
public class Update_Menu extends javax.swing.JFrame {

    /**
     * Creates new form stnd_menu
     */
    public Update_Menu() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        update_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        snfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        itemname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        itemprice = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        rvmbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        categoryComboBox = new javax.swing.JComboBox<>();
        backbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        update_table.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_table.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        update_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "S.N", "Item", "Price"
            }
        ));
        jScrollPane1.setViewportView(update_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 369, 247));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("S.N:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        snfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(snfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 76, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        itemname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        itemname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnameActionPerformed(evt);
            }
        });
        getContentPane().add(itemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 154, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        itemprice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(itemprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 150, -1));

        addbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addbtn.setText("Add");
        addbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 259, 80, 40));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 6, -1, -1));

        rvmbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rvmbtn.setText("Remove");
        rvmbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rvmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rvmbtnActionPerformed(evt);
            }
        });
        getContentPane().add(rvmbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 90, 40));

        updatebtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 90, 40));

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drinks", "Snacks", "Desserts" }));
        categoryComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(categoryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 43, -1, -1));

        backbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backbtn.setText("<<Back");
        backbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tes.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
            String item = itemname.getText();
            String price = itemprice.getText();
            String serial = snfield.getText();
            
            String category = (String) categoryComboBox.getSelectedItem();
        if (itemname.getText().equals("") || snfield.getText().equals("")|| itemprice.getText().equals(""))
        {        
        JOptionPane.showMessageDialog(this,"Please Enter All The Data!!");
         }
      else{            
            Object[] menu = {category,serial,item,price};
            DefaultTableModel tbm = (DefaultTableModel) update_table.getModel();
             tbm.addRow(menu);
             itemname.setText("");
             snfield.setText("");
             itemprice.setText("");
            
    }//GEN-LAST:event_addbtnActionPerformed
     }
    
    private void rvmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rvmbtnActionPerformed

        int selectedRow = update_table.getSelectedRow();
        if(selectedRow >=0){
             DefaultTableModel dmodel = (DefaultTableModel)update_table.getModel();
             dmodel.removeRow(selectedRow);
        }
        try {
                DefaultTableModel model = (DefaultTableModel) update_table.getModel();
                
                if(update_table.getSelectedRow()==0){
                    model.removeRow(update_table.getSelectedRow());
                }
                else{
                    if(update_table.getRowCount()==0){
                        JOptionPane.showMessageDialog(this, "Table is Emply.");
                    }
                    else{
                            JOptionPane.showMessageDialog(this,"Please select single Row for Delete");
                            }
                }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rvmbtnActionPerformed
    private static void writeDataToFile(ArrayList<ArrayList<String>> data, String fileName){
        try(PrintWriter write = new PrintWriter(new BufferedWriter(new FileWriter(fileName,true)))) {
            for(ArrayList<String> row :data){
                write.println(String.join(",",row));
            }
            System.out.println("Data Written To "+ fileName);
        } catch (Exception e) {
        }
    }
    
    
    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
           ArrayList<ArrayList<String>> data = new ArrayList<>();
            int rowCount = update_table.getRowCount();
            for(int i = 0; i < rowCount; i++){
                ArrayList<String> row = new ArrayList<>();
                for(int j =0; j <update_table.getColumnCount();j++){
                    row.add((String) update_table.getValueAt(i,j));
                }
                data.add(row);
            }
         writeDataToFile(data,"D:\\netbeans_projects\\JavaApplication2\\textfile\\menu.txt");
         JOptionPane.showMessageDialog(this,"Added to file");
         DefaultTableModel newTableModel = new DefaultTableModel();
         newTableModel.addColumn("Category");
         newTableModel.addColumn("S.N");
         newTableModel.addColumn("Item");
         newTableModel.addColumn("Price");
         update_table.setModel(newTableModel);
    }//GEN-LAST:event_updatebtnActionPerformed

    private void itemnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemnameActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        Manager_DashBoard mgdh = new Manager_DashBoard();
        this.hide();
        mgdh.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed
        
    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
                 
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JTextField itemname;
    private javax.swing.JTextField itemprice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton rvmbtn;
    private javax.swing.JTextField snfield;
    private javax.swing.JLabel time;
    private javax.swing.JTable update_table;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

    private void getText() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
